apiVersion: skaffold/v2beta12
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: cheatcodesam/hack-client
      context: frontend
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
          - src: "src/**/*.jsx"
            dest: .
          - src: "src/**/*.css"
            dest: .
          - src: "src/**/*.wasm"
            dest: .
          - src: "src/**/*.data"
            dest: .
          - src: "src/**/*.html"
            dest: .
    - image: cheatcodesam/hack-server
      context: backend
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "apps/**/*.py"
            dest: .
          - src: "apps/**/*.html"
            dest: .
          - src: "devproject/**/*.py"
            dest: .
deploy:
  kubectl:
    manifests:
      - ./k8s/*
