# Generated by Django 4.0.4 on 2022-04-23 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=50)),
                ('right_answer', models.IntegerField()),
                ('answer1', models.CharField(max_length=50, null=True)),
                ('answer2', models.CharField(max_length=50, null=True)),
                ('answer3', models.CharField(max_length=50, null=True)),
                ('answer4', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='war.question')),
            ],
        ),
    ]
